# #
# # This action will fetch the commits across the org
# # and commit the changes to the repository.
# # This is set to run every 6 hours.
# #

name: Fetch contributions
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
      with:
          node-version: '16'
    - name: Install dependencies
      run: yarn
    - name: create env file
      run: |
        cd scripts
        touch .env
        echo REPO_NAMES=${{ secrets.REPO_NAMES }} >> .env
        echo ORG=${{ secrets.ORG }} >> .env
    - name: Fetch commits
      run: |
        cd scripts
        yarn fetch:commit
    - name: Push the changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: fetch and update contributions
        commit_author: GH Actions <actions@github.com>
